name: dart_webrtc
description: Use the dart/js library to re-wrap the webrtc js interface of the browser, to adapted common browsers.
version: 1.1.3
homepage: https://github.com/flutter-webrtc/dart-webrtc
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  js: ^0.6.4  
  platform_detect:
    git:
      url: https://github.com/powntheep/platform_detect.git
      ref: master
  web: 0.4.0
  webrtc_interface: 1.1.2
  
dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ^4.0.0
  http: ^0.13.3
  import_sorter: ^4.6.0
  pedantic: ^1.9.0
  protoo_client: ^0.3.0
  test: ^1.15.4
